name: Moodle Plugin CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
      moodleapp:
        image: moodlehq/moodleapp:next-test
        ports:
          - 8100:80

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          path: plugin

      - name: Setup PHP 8.0
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          ini-values: max_input_vars=5000
          coverage: none

      - name: Initialise moodle-plugin-ci
        run: |
          git clone https://github.com/NoelDeMartin/moodle-plugin-ci --branch moodle-app-wip ci
          composer install -d ./ci
          echo $(cd ci/bin; pwd) >> $GITHUB_PATH
          echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
          sudo locale-gen en_AU.UTF-8
          echo "NVM_DIR=$HOME/.nvm" >> $GITHUB_ENV

      - name: Add local_moodleappbehat
        run: moodle-plugin-ci add-plugin moodlehq/moodle-local_moodleappbehat --branch integration

      - name: Install moodle-plugin-ci
        run: |
          moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1
        env:
          DB: pgsql
          MOODLE_BRANCH: MOODLE_400_STABLE
          MOODLE_BEHAT_DEFAULT_BROWSER: chrome
          MOODLE_BEHAT_IONIC_WWWROOT: http://localhost:8100

      - name: PHP Lint
        run: moodle-plugin-ci phplint

      - name: PHP Mess Detector
        run: moodle-plugin-ci phpmd

      - name: Validating
        run: moodle-plugin-ci validate

      - name: Behat features
        run: moodle-plugin-ci behat --profile chrome
